name: On pull request

on:
    pull-request:
        jobs:
            PR:
                runs-on: ubuntu-latest
                steps:
                    - name: "Update"
                    run: echo "created a pull request"