name: On push request

on:
  push:

jobs:
  hello-world:
    steps:
      - name: "Hello world"
        run: echo "Hello world"
  another-job:
    steps:
      - name: "Update"
        run: echo "we've updated out code"
